# Generated by Django 5.2.6 on 2026-01-24 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_table', '0001_initial'),
        ('scheduling', '0005_tkblog_thoikhoabieu_is_deleted_alter_bomon_ma_bo_mon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoMonProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Bộ môn',
                'verbose_name_plural': 'Các Bộ môn',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('scheduling.bomon',),
        ),
        migrations.CreateModel(
            name='DotXepProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Đợt xếp lịch',
                'verbose_name_plural': 'Đợt xếp lịch',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('scheduling.dotxep',),
        ),
        migrations.CreateModel(
            name='DuKienDTProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Dự kiến dạy học',
                'verbose_name_plural': 'Dự kiến dạy học',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('scheduling.dukiendt',),
        ),
        migrations.CreateModel(
            name='GiangVienProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Giảng viên',
                'verbose_name_plural': 'Giảng viên',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('scheduling.giangvien',),
        ),
        migrations.CreateModel(
            name='GVDayMonProxy',
            fields=[
            ],
            options={
                'verbose_name': 'GV dạy môn',
                'verbose_name_plural': 'GV dạy môn',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('scheduling.gvdaymon',),
        ),
        migrations.CreateModel(
            name='KhoaProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Khoa',
                'verbose_name_plural': 'Các Khoa',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('scheduling.khoa',),
        ),
        migrations.CreateModel(
            name='KhungTGProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Khung thời gian',
                'verbose_name_plural': 'Khung thời gian',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('scheduling.khungtg',),
        ),
        migrations.CreateModel(
            name='LopMonHocProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Lớp môn học',
                'verbose_name_plural': 'Lớp môn học',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('scheduling.lopmonhoc',),
        ),
        migrations.CreateModel(
            name='MonHocProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Môn học',
                'verbose_name_plural': 'Môn học',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('scheduling.monhoc',),
        ),
        migrations.CreateModel(
            name='NgayNghiCoDinhProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Ngày nghỉ cố định',
                'verbose_name_plural': 'Ngày nghỉ cố định',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('scheduling.ngaynghicodinh',),
        ),
        migrations.CreateModel(
            name='NgayNghiDotProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Ngày nghỉ theo đợt',
                'verbose_name_plural': 'Ngày nghỉ theo đợt',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('scheduling.ngaynghidot',),
        ),
        migrations.CreateModel(
            name='NguyenVongProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Nguyện vọng',
                'verbose_name_plural': 'Nguyện vọng giảng viên',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('scheduling.nguyenvong',),
        ),
        migrations.CreateModel(
            name='PhanCongProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Phân công',
                'verbose_name_plural': 'Phân công giảng dạy',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('scheduling.phancong',),
        ),
        migrations.CreateModel(
            name='PhongHocProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Phòng học',
                'verbose_name_plural': 'Phòng học',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('scheduling.phonghoc',),
        ),
        migrations.CreateModel(
            name='RangBuocMemProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Ràng buộc mềm',
                'verbose_name_plural': 'Ràng buộc mềm',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('scheduling.rangbuocmem',),
        ),
        migrations.CreateModel(
            name='RangBuocTrongDotProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Ràng buộc trong đợt',
                'verbose_name_plural': 'Ràng buộc trong đợt',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('scheduling.rangbuoctrongdot',),
        ),
        migrations.CreateModel(
            name='ThoiKhoaBieuProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Thời khóa biểu',
                'verbose_name_plural': 'Thời khóa biểu',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('scheduling.thoikhoabieu',),
        ),
        migrations.CreateModel(
            name='TimeSlotProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Time Slot',
                'verbose_name_plural': 'Time Slots',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('scheduling.timeslot',),
        ),
    ]
