# Generated by Django 5.2.6 on 2025-10-25 07:12

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scheduling', '0002_alter_gvdaymon_id_alter_nguyenvong_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SapLichProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Công cụ sắp lịch',
                'verbose_name_plural': 'Công cụ sắp lịch',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('scheduling.dotxep',),
        ),
    ]
