# Generated by Django 5.2.6 on 2025-12-28 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sap_lich', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SapLich',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Sắp lịch',
                'verbose_name_plural': 'Sắp lịch',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='SapLichProxy',
        ),
    ]
