"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 4.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

import os, random, string
from pathlib import Path
from dotenv import load_dotenv
from str2bool import str2bool

load_dotenv()  # take environment variables from .env.

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'Super_Secr3t_9999')

# Enable/Disable DEBUG Mode
DEBUG = str2bool(os.environ.get('DEBUG', 'false'))
#print(' DEBUG -> ' + str(DEBUG) ) 

# Docker HOST
ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    'scheduling-web.azurewebsites.net',  # Azure App Service - short domain
    'scheduling-web-dzd2dedxcwe2d3hx.southeastasia-01.azurewebsites.net',  # Azure App Service - full domain
]

# Add here your deployment HOSTS
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:8000', 
    'http://localhost:5085', 
    'http://127.0.0.1:8000', 
    'http://127.0.0.1:5085',
    'https://scheduling-web.azurewebsites.net',  # Azure App Service
    'https://scheduling-web-dzd2dedxcwe2d3hx.southeastasia-01.azurewebsites.net',  # Azure App Service - full domain
]

RENDER_EXTERNAL_HOSTNAME = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if RENDER_EXTERNAL_HOSTNAME:    
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)

# Application definition

INSTALLED_APPS = [
    'jazzmin',
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Serve UI pages
    "apps.pages",

    # Dynamic DT
    "apps.data_table",

    # Dynamic API
    "apps.dyn_api",

    # Charts
    "apps.charts",
    
    # Scheduling System - NEW
    "apps.scheduling",
    
    # Sap Lich - Scheduling Tools Container
    "apps.sap_lich",

    # Tooling API-GEN
    'rest_framework',            # Include DRF           # <-- NEW 
    'rest_framework.authtoken',  # Include DRF Auth      # <-- NEW
    'django_filters',            # For filtering in DRF   # <-- NEW
    
    # API Documentation
    'drf_spectacular',           # OpenAPI 3.0 Schema + Swagger UI
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

HOME_TEMPLATES = os.path.join(BASE_DIR, 'templates')

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [HOME_TEMPLATES],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "apps.sap_lich.context_processors.user_role_context",  # Custom context processor
                "apps.sap_lich.jazzmin_helpers.jazzmin_menu_context",  # Jazzmin menu filter
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases
# Support both Azure SQL and local SQL Server

DB_ENGINE   = os.getenv('DB_ENGINE')
DB_USER     = os.getenv('DB_USERNAME')  # Azure uses DB_USERNAME
DB_PASSWORD = os.getenv('DB_PASS')      # Azure uses DB_PASS
DB_HOST     = os.getenv('DB_HOST')
DB_PORT     = os.getenv('DB_PORT', '1433')
DB_NAME     = os.getenv('DB_NAME')

# Auto-detect ODBC driver (try 18 first, fallback to 17)
DB_DRIVER = os.getenv('DB_DRIVER')
if not DB_DRIVER:
    try:
        import pyodbc
        available_drivers = [d for d in pyodbc.drivers() if 'ODBC Driver' in d and 'SQL Server' in d]
        if available_drivers:
            # Prefer version 18, then 17
            for driver in ['ODBC Driver 18 for SQL Server', 'ODBC Driver 17 for SQL Server']:
                if driver in available_drivers:
                    DB_DRIVER = driver
                    break
            if not DB_DRIVER:
                DB_DRIVER = available_drivers[0]  # Use first available
        else:
            DB_DRIVER = 'ODBC Driver 18 for SQL Server'  # Default for Azure
    except:
        DB_DRIVER = 'ODBC Driver 18 for SQL Server'  # Default

DB_USE_WINDOWS_AUTH = os.getenv('DB_USE_WINDOWS_AUTH', 'false').lower() == 'true'

if DB_ENGINE and DB_NAME and (DB_USER or DB_USE_WINDOWS_AUTH):
    if DB_ENGINE == 'mssql':
        # Detect Azure SQL by checking if hostname contains '.database.windows.net'
        is_azure_sql = '.database.windows.net' in DB_HOST
        
        if is_azure_sql:
            # Azure SQL: Must explicitly set Encrypt=yes
            _mssql_options = {
                'driver': DB_DRIVER,
                'extra_params': 'Encrypt=yes;TrustServerCertificate=no;Connection Timeout=30;',
            }
        else:
            # Local SQL Server
            _mssql_options = {
                'driver': DB_DRIVER,
                'extra_params': 'TrustServerCertificate=yes',
            }
        
        # With Windows Authentication we should not pass user/password
        if DB_USE_WINDOWS_AUTH:
            _mssql_options['extra_params'] = 'TrustServerCertificate=yes;'
            _mssql_options['trusted_connection'] = 'yes'

        DATABASES = {
            'default': {
                'ENGINE': 'mssql',
                'NAME': DB_NAME,
                'USER': None if DB_USE_WINDOWS_AUTH else DB_USER,
                'PASSWORD': None if DB_USE_WINDOWS_AUTH else DB_PASSWORD,
                'HOST': DB_HOST,
                'PORT': DB_PORT or None,
                'OPTIONS': _mssql_options,
            },
        }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': 'db.sqlite3',
        }
    }

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "vi"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
)

# WhiteNoise static files storage for production
# This ensures static files are compressed and have unique hashes for cache busting
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

LOGIN_REDIRECT_URL = '/'
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Auth settings
LOGIN_URL = '/login/'  # Trang login cho users thông thường
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# ### DYNAMIC_DATATB Settings ###
DYNAMIC_DATATB = {
    # SLUG -> Import_PATH 
    'Sản phẩm'  : "apps.pages.models.Product",
    'Khoa'  : "apps.scheduling.models.Khoa",
    'Tổ bộ môn'  : "apps.scheduling.models.BoMon",
    'Giảng viên'  : "apps.scheduling.models.GiangVien",
    'Môn học'  : "apps.scheduling.models.MonHoc",
    'Giáo viên dạy môn'  : "apps.scheduling.models.GVDayMon",
    'Khung thời gian'  : "apps.scheduling.models.KhungTG",
    'Ràng buộc mềm'  : "apps.scheduling.models.RangBuocMem",
    'Phòng học'  : "apps.scheduling.models.PhongHoc",
    'Lớp môn học'  : "apps.scheduling.models.LopMonHoc",
    'Dự kiến dạy học'  : "apps.scheduling.models.DuKienDT",
    'Đợt xếp'  : "apps.scheduling.models.DotXep",
    'Nguyện vọng'  : "apps.scheduling.models.NguyenVong",
    'Phân công'  : "apps.scheduling.models.PhanCong",
    'Thời gian'  : "apps.scheduling.models.TimeSlot",
    'Ràng buộc trong đợt'  : "apps.scheduling.models.RangBuocTrongDot",
    'Thời khóa biểu'  : "apps.scheduling.models.ThoiKhoaBieu",
}
########################################

# Syntax: URI -> Import_PATH
DYNAMIC_API = {
    # SLUG -> Import_PATH 
    'product'  : "apps.pages.models.Product",
}

# JAZZMIN Configuration
JAZZMIN_SETTINGS = {
    "site_title": "Quản lý lịch dạy học",
    "site_header": "Hệ thống quản lý lịch dạy học",
    "site_brand": "TKB",
    "welcome_sign": "Chào mừng đến hệ thống quản lý lịch dạy học",
    "copyright": "",
    "search_model": "auth.User",
    "topmenu_links": [
        {"name": "Trang chủ", "url": "/"},
        {"name": "Dữ liệu", "url": "/data_table/"},
    ],
    "usermenu_links": [
        {"name": "Hồ sơ", "url": "/user-profile/", "icon": "fas fa-user-circle"},
    ],
    "show_sidebar": True,
    "navigation_expanded": False,
    # Order apps - put "Sắp lịch" first
    "order_with_respect_to": ["sap_lich", "scheduling", "pages", "data_table"],
    # Ẩn model SapLich (dummy model) và tất cả models scheduling (sẽ hiện qua custom links)
    "hide_models": [
        "sap_lich.SapLich",
        "pages.Product",
        "pages.UserProfile",
        "scheduling.Khoa",
        "scheduling.BoMon",
        "scheduling.GiangVien",
        "scheduling.GVDayMon",
        "scheduling.MonHoc",
        "scheduling.PhongHoc",
        "scheduling.LopMonHoc",
        "scheduling.DotXep",
        "scheduling.PhanCong",
        "scheduling.KhungTG",
        "scheduling.RangBuocMem",
        "scheduling.RangBuocTrongDot",
        "scheduling.DuKienDT",
        "scheduling.NgayNghiCoDinh",
        "scheduling.NgayNghiDot",
        "scheduling.NguyenVong",
        "scheduling.TimeSlot",
        "scheduling.ThoiKhoaBieu",
        "data_table.HideShowFilter",
        "data_table.ModelFilter",
        "data_table.PageItems",
    ],
    # Hide entire apps
    # auth app sẽ được ẩn động dựa vào has_module_permission trong custom admin
    "hide_apps": ["authtoken"],  # Ẩn authtoken cho tất cả users
    # Show all apps including new ones
    "show_ui_builder": False,
    # Custom links under "Sắp lịch" in sidebar
    # SỬA: Dùng permissions chuẩn theo model thay vì auth.view_user
    "custom_links": {
        "sap_lich": [
            {
                "name": "Sắp lịch (Thuật toán)",
                "url": "/admin/sap_lich/algo-scheduler/",
                "icon": "fas fa-robot",
                "permissions": ["auth.add_user"]  # Chỉ admin/superuser
            },
            {
                "name": "Chat Bot Hỗ trợ (LLM)",
                "url": "/admin/sap_lich/llm-scheduler/",
                "icon": "fas fa-comments",
                "permissions": ["auth.add_user"]  # Chỉ admin/superuser
            },
        ],
        "scheduling": [
            {
                "name": "Xem Thời Khóa Biểu",
                "url": "/admin/sap_lich/thoikhoabieu/",
                "icon": "fas fa-calendar-alt",
                "permissions": ["scheduling.view_thoikhoabieu"]  # Tất cả role có quyền xem TKB
            },
            {
                "name": "Quản lý TKB",
                "url": "/admin/sap_lich/tkb-manage/",
                "icon": "fas fa-edit",
                "permissions": ["scheduling.change_thoikhoabieu"]  # Admin + Trưởng Khoa
            },
        ],
        "data_table": [
            
            {
                "name": "Khoa",
                "url": "/admin/scheduling/khoa/",
                "icon": "fas fa-building",
                "permissions": ["scheduling.view_khoa"]  # Admin + Trưởng Khoa
            },
            {
                "name": "Bộ môn",
                "url": "/admin/scheduling/bomon/",
                "icon": "fas fa-sitemap",
                "permissions": ["scheduling.view_bomon"]  # Admin + Trưởng Khoa + Trưởng Bộ Môn
            },
            {
                "name": "Giảng viên",
                "url": "/admin/scheduling/giangvien/",
                "icon": "fas fa-chalkboard-user",
                "permissions": ["scheduling.view_giangvien"]  # Admin + Trưởng Khoa + Trưởng Bộ Môn
            },
            {
                "name": "Môn học",
                "url": "/admin/scheduling/monhoc/",
                "icon": "fas fa-book",
                "permissions": ["scheduling.view_monhoc"]  # Admin + Trưởng Khoa
            },
            {
                "name": "GV dạy môn",
                "url": "/admin/scheduling/gvdaymon/",
                "icon": "fas fa-user-tie",
                "permissions": ["scheduling.view_gvdaymon"]  # Admin + Trưởng Khoa
            },
            {
                "name": "Phòng học",
                "url": "/admin/scheduling/phonghoc/",
                "icon": "fas fa-door-open",
                "permissions": ["scheduling.view_phonghoc"]  # Admin + Trưởng Khoa
            },
            {
                "name": "Lớp môn học",
                "url": "/admin/scheduling/lopmonhoc/",
                "icon": "fas fa-graduation-cap",
                "permissions": ["scheduling.view_lopmonhoc"]  # Admin + Trưởng Khoa
            },
            {
                "name": "Đợt xếp",
                "url": "/admin/scheduling/dotxep/",
                "icon": "fas fa-calendar-days",
                "permissions": ["scheduling.view_dotxep"]  # Admin + Trưởng Khoa
            },
            {
                "name": "Phân công",
                "url": "/admin/scheduling/phancong/",
                "icon": "fas fa-handshake",
                "permissions": ["scheduling.view_phancong"]  # Admin + Trưởng Khoa + Trưởng Bộ Môn
            },
            {
                "name": "Khung thời gian",
                "url": "/admin/scheduling/khungtg/",
                "icon": "fas fa-hourglass-half",
                "permissions": ["scheduling.view_khungtg"]  # Admin
            },
            {
                "name": "Ràng buộc mềm",
                "url": "/admin/scheduling/rangbuocmem/",
                "icon": "fas fa-wave-square",
                "permissions": ["scheduling.view_rangbuocmem"]  # Admin
            },
            {
                "name": "Ràng buộc trong đợt",
                "url": "/admin/scheduling/rangbuoctrongdot/",
                "icon": "fas fa-shield-alt",
                "permissions": ["scheduling.view_rangbuoctrongdot"]  # Admin
            },
            {
                "name": "Dự kiến dạy học",
                "url": "/admin/scheduling/dukiendt/",
                "icon": "fas fa-clipboard-check",
                "permissions": ["scheduling.view_dukiendt"]  # Admin
            },
            {
                "name": "Ngày nghỉ cố định",
                "url": "/admin/scheduling/ngaynghicodinh/",
                "icon": "fas fa-calendar-xmark",
                "permissions": ["scheduling.view_ngaynghicodinh"]  # Admin
            },
            {
                "name": "Ngày nghỉ đợt",
                "url": "/admin/scheduling/ngaynghidot/",
                "icon": "fas fa-calendar-minus",
                "permissions": ["scheduling.view_ngaynghidot"]  # Admin
            },
            {
                "name": "Nguyện vọng",
                "url": "/admin/scheduling/nguyenvong/",
                "icon": "fas fa-heart",
                "permissions": ["scheduling.view_nguyenvong"]  # Tất cả user
            },
            {
                "name": "Time Slot",
                "url": "/admin/scheduling/timeslot/",
                "icon": "fas fa-hourglass-end",
                "permissions": ["scheduling.view_timeslot"]  # Admin
            },
            {
                "name": "Thời khóa biểu",
                "url": "/admin/scheduling/thoikhoabieu/",
                "icon": "fas fa-calendar-check",
                "permissions": ["scheduling.view_thoikhoabieu"]  # Tất cả role
            },
            {
                "name": "Hide show filters",
                "url": "/admin/data_table/hideshowfilter/",
                "icon": "fas fa-eye-slash",
                "permissions": ["auth.view_user"]
            },
            {
                "name": "Model filters",
                "url": "/admin/data_table/modelfilter/",
                "icon": "fas fa-filter",
                "permissions": ["auth.view_user"]
            },
            {
                "name": "Page items",
                "url": "/admin/data_table/pageitems/",
                "icon": "fas fa-list",
                "permissions": ["auth.view_user"]
            },
        ],
        "pages": [
            {
                "name": "Hồ sơ cá nhân",
                "url": "/user-profile/",
                "icon": "fas fa-user-circle",
                "permissions": []  # Không cần permission - tất cả user đều thấy
            },
        ],
        "auth": [
            {
                "name": "Phân quyền User/Role",
                "url": "/admin/scheduling/assign-roles/",
                "icon": "fas fa-user-shield",
                "permissions": ["auth.add_user"]  # Chỉ admin
            },
           
        ]
    },
    "icons": {
        # Sap Lich app icon
        "sap_lich": "fas fa-calendar-plus",
        
        # Pages app icon (Hồ sơ cá nhân)
        "pages": "fas fa-user-circle",
        
        "auth": "fas fa-lock",
        "auth.user": "fas fa-user",
        "auth.group": "fas fa-users",
        
        # Auth token (DRF authtoken)
        "authtoken": "fas fa-key",
        "authtoken.tokenproxy": "fas fa-user-shield",
        "scheduling": "fas fa-calendar-check",
        
        # Data table app
        "data_table": "fas fa-table",

        # REST framework / tooling
        "rest_framework": "fas fa-cubes",

        # Scheduling models
        "scheduling.khoa": "fas fa-building",
        "scheduling.bomon": "fas fa-sitemap",
        "scheduling.giangvien": "fas fa-chalkboard-user",
        "scheduling.gvdaymon": "fas fa-user-tie",  # Giáo viên dạy môn
        "scheduling.monhoc": "fas fa-book",
        "scheduling.phonghoc": "fas fa-door-open",
        "scheduling.lopmonhoc": "fas fa-graduation-cap",
        "scheduling.dotxep": "fas fa-calendar-days",
        "scheduling.phancong": "fas fa-handshake",
        "scheduling.khungtg": "fas fa-hourglass-half",  # Khung thời gian
        "scheduling.rangbuocmem": "fas fa-wave-square",  # Ràng buộc mềm
        "scheduling.rangbuoctrongdot": "fas fa-shield-alt",  # Ràng buộc trong đợt
        "scheduling.dukiendt": "fas fa-clipboard-check",  # Dự kiến dạy-học (fixed: was dukilendtao)
        "scheduling.ngaynghicodinh": "fas fa-calendar-xmark",  # Ngày nghỉ cố định
        "scheduling.ngaynghidot": "fas fa-calendar-minus",  # Ngày nghỉ theo đợt
        
        "scheduling.nguyenvong": "fas fa-heart",
        "scheduling.timeslot": "fas fa-hourglass-end",
        "scheduling.thoikhoabieu": "fas fa-calendar-check",
    },
    "default_icon_children": "fas fa-chevron-right",
    "related_modal_active": False,
    "custom_css": "assets/css/jazzmin-purple.css",
    "custom_js": None,
    "show_ui_builder": False,
    "changeform_format": "horizontal_tabs",
    "language_code": "vi",

}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50,
    # OpenAPI Schema Generator (drf-spectacular)
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# DRF-Spectacular Settings (OpenAPI 3.0 Documentation)
SPECTACULAR_SETTINGS = {
    'TITLE': 'Scheduling System API',
    'DESCRIPTION': '''
## Hệ thống Xếp Thời Khóa Biểu Tự Động

API documentation cho hệ thống quản lý và xếp lịch thời khóa biểu đại học.

### Các tính năng chính:
- **Quản lý Khoa/Bộ môn**: CRUD operations cho khoa và bộ môn
- **Quản lý Giảng viên**: Quản lý thông tin giảng viên, nguyện vọng
- **Quản lý Môn học**: Quản lý môn học, lớp môn học
- **Quản lý Phòng học**: Quản lý phòng học theo loại và sức chứa
- **Xếp Thời Khóa Biểu**: Thuật toán tự động xếp lịch (CP-SAT Solver)
- **AI Chatbot**: Hỗ trợ chatbot AI (Gemini)

### Authentication:
- Session Authentication (cho web interface)
- Token Authentication (cho API clients)
    ''',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'CONTACT': {
        'name': 'Scheduling System Team',
        'email': 'support@scheduling.edu.vn',
    },
    'LICENSE': {
        'name': 'MIT License',
    },
    'TAGS': [
        {'name': 'Khoa', 'description': 'Quản lý Khoa'},
        {'name': 'Bộ Môn', 'description': 'Quản lý Bộ môn'},
        {'name': 'Giảng Viên', 'description': 'Quản lý Giảng viên'},
        {'name': 'Môn Học', 'description': 'Quản lý Môn học'},
        {'name': 'Phòng Học', 'description': 'Quản lý Phòng học'},
        {'name': 'Lớp Môn Học', 'description': 'Quản lý Lớp môn học'},
        {'name': 'Thời Khóa Biểu', 'description': 'Xem và quản lý thời khóa biểu'},
        {'name': 'Schedule Generation', 'description': 'Tạo thời khóa biểu tự động'},
        {'name': 'Chatbot', 'description': 'AI Chatbot hỗ trợ'},
    ],
    'COMPONENT_SPLIT_REQUEST': True,
    'SORT_OPERATIONS': False,
}
########################################

# AI Configuration (Migrated from src/config.py - AIConfig)
GEMINI_API_KEY = os.getenv('GEMINI_API_KEY')
AI_MODEL_NAME = os.getenv('AI_MODEL_NAME', 'gemini-2.5-flash')
AI_TEMPERATURE = float(os.getenv('AI_TEMPERATURE', '0'))
AI_MAX_OUTPUT_TOKENS = int(os.getenv('AI_MAX_OUTPUT_TOKENS', '8192'))

# System Configuration (Migrated from src/config.py - SystemConfig)
LOG_LEVEL = os.getenv('LOG_LEVEL', 'INFO')
SCHEDULE_OUTPUT_DIR = os.getenv('SCHEDULE_OUTPUT_DIR', './schedules')

# Ensure output directory exists
import os as _os
if not _os.path.exists(SCHEDULE_OUTPUT_DIR):
    _os.makedirs(SCHEDULE_OUTPUT_DIR)
########################################
