# Generated by Django 5.2.6 on 2025-10-17 08:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoMon',
            fields=[
                ('ma_bo_mon', models.CharField(db_column='MaBoMon', max_length=12, primary_key=True, serialize=False, verbose_name='Mã bộ môn')),
                ('ten_bo_mon', models.CharField(db_column='TenBoMon', max_length=200, verbose_name='Tên bộ môn')),
            ],
            options={
                'verbose_name': 'Bộ môn',
                'verbose_name_plural': 'Các Bộ môn',
                'db_table': 'tb_BO_MON',
                'ordering': ['ma_bo_mon'],
            },
        ),
        migrations.CreateModel(
            name='DuKienDT',
            fields=[
                ('ma_du_kien_dt', models.CharField(db_column='MaDuKienDT', max_length=15, primary_key=True, serialize=False, verbose_name='Mã dự kiến ĐT')),
                ('nam_hoc', models.CharField(blank=True, db_column='NamHoc', max_length=9, null=True, verbose_name='Năm học')),
                ('hoc_ky', models.SmallIntegerField(choices=[(1, 'Học kỳ 1'), (2, 'Học kỳ 2'), (3, 'Học kỳ Hè'), (4, 'Học kỳ 4')], db_column='HocKy', verbose_name='Học kỳ')),
                ('ngay_bd', models.DateTimeField(blank=True, db_column='NgayBD', null=True, verbose_name='Ngày bắt đầu')),
                ('ngay_kt', models.DateTimeField(blank=True, db_column='NgayKT', null=True, verbose_name='Ngày kết thúc')),
                ('mo_ta_hoc_ky', models.CharField(blank=True, db_column='MoTaHocKy', max_length=100, null=True, verbose_name='Mô tả học kỳ')),
            ],
            options={
                'verbose_name': 'Dự kiến đào tạo',
                'verbose_name_plural': 'Dự kiến đào tạo',
                'db_table': 'tb_DUKIEN_DT',
                'ordering': ['-nam_hoc', '-hoc_ky'],
            },
        ),
        migrations.CreateModel(
            name='Khoa',
            fields=[
                ('ma_khoa', models.CharField(db_column='MaKhoa', max_length=12, primary_key=True, serialize=False, verbose_name='Mã khoa')),
                ('ten_khoa', models.CharField(db_column='TenKhoa', max_length=200, verbose_name='Tên khoa')),
            ],
            options={
                'verbose_name': 'Khoa',
                'verbose_name_plural': 'Các Khoa',
                'db_table': 'tb_KHOA',
                'ordering': ['ma_khoa'],
            },
        ),
        migrations.CreateModel(
            name='KhungTG',
            fields=[
                ('ma_khung_gio', models.SmallIntegerField(db_column='MaKhungGio', primary_key=True, serialize=False, verbose_name='Mã ca')),
                ('ten_ca', models.CharField(blank=True, db_column='TenCa', max_length=50, null=True, verbose_name='Tên ca')),
                ('gio_bat_dau', models.TimeField(db_column='GioBatDau', verbose_name='Giờ bắt đầu')),
                ('gio_ket_thuc', models.TimeField(db_column='GioKetThuc', verbose_name='Giờ kết thúc')),
                ('so_tiet', models.SmallIntegerField(db_column='SoTiet', default=3, verbose_name='Số tiết')),
            ],
            options={
                'verbose_name': 'Khung thời gian',
                'verbose_name_plural': 'Khung thời gian',
                'db_table': 'tb_KHUNG_TG',
                'ordering': ['ma_khung_gio'],
            },
        ),
        migrations.CreateModel(
            name='MonHoc',
            fields=[
                ('ma_mon_hoc', models.CharField(db_column='MaMonHoc', max_length=10, primary_key=True, serialize=False, verbose_name='Mã môn học')),
                ('ten_mon_hoc', models.CharField(db_column='TenMonHoc', max_length=200, verbose_name='Tên môn học')),
                ('so_tin_chi', models.SmallIntegerField(blank=True, db_column='SoTinChi', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Số tín chỉ')),
                ('so_tiet_lt', models.SmallIntegerField(blank=True, db_column='SoTietLT', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Số tiết LT')),
                ('so_tiet_th', models.SmallIntegerField(blank=True, db_column='SoTietTH', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Số tiết TH')),
                ('so_tuan', models.SmallIntegerField(db_column='SoTuan', default=15, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Số tuần')),
            ],
            options={
                'verbose_name': 'Môn học',
                'verbose_name_plural': 'Môn học',
                'db_table': 'tb_MON_HOC',
                'ordering': ['ma_mon_hoc'],
            },
        ),
        migrations.CreateModel(
            name='PhongHoc',
            fields=[
                ('ma_phong', models.CharField(db_column='MaPhong', max_length=12, primary_key=True, serialize=False, verbose_name='Mã phòng')),
                ('loai_phong', models.CharField(blank=True, db_column='LoaiPhong', max_length=100, null=True, verbose_name='Loại phòng')),
                ('suc_chua', models.SmallIntegerField(blank=True, db_column='SucChua', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Sức chứa')),
                ('thiet_bi', models.CharField(blank=True, db_column='ThietBi', max_length=400, null=True, verbose_name='Thiết bị')),
                ('ghi_chu', models.CharField(blank=True, db_column='GhiChu', max_length=200, null=True, verbose_name='Ghi chú')),
            ],
            options={
                'verbose_name': 'Phòng học',
                'verbose_name_plural': 'Phòng học',
                'db_table': 'tb_PHONG_HOC',
                'ordering': ['ma_phong'],
            },
        ),
        migrations.CreateModel(
            name='RangBuocMem',
            fields=[
                ('ma_rang_buoc', models.CharField(db_column='MaRangBuoc', max_length=15, primary_key=True, serialize=False, verbose_name='Mã ràng buộc')),
                ('ten_rang_buoc', models.CharField(db_column='TenRangBuoc', max_length=200, verbose_name='Tên ràng buộc')),
                ('mo_ta', models.CharField(blank=True, db_column='MoTa', max_length=500, null=True, verbose_name='Mô tả')),
                ('trong_so', models.FloatField(db_column='TrongSo', verbose_name='Trọng số')),
            ],
            options={
                'verbose_name': 'Ràng buộc mềm',
                'verbose_name_plural': 'Ràng buộc mềm',
                'db_table': 'tb_RANG_BUOC_MEM',
                'ordering': ['ma_rang_buoc'],
            },
        ),
        migrations.CreateModel(
            name='DotXep',
            fields=[
                ('ma_dot', models.CharField(db_column='MaDot', max_length=20, primary_key=True, serialize=False, verbose_name='Mã đợt')),
                ('ten_dot', models.CharField(blank=True, db_column='TenDot', max_length=200, null=True, verbose_name='Tên đợt')),
                ('trang_thai', models.CharField(choices=[('DRAFT', 'Draft'), ('RUNNING', 'Running'), ('LOCKED', 'Locked'), ('PUBLISHED', 'Published')], db_column='TrangThai', default='DRAFT', max_length=20, verbose_name='Trạng thái')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True, db_column='NgayTao', verbose_name='Ngày tạo')),
                ('ngay_khoa', models.DateTimeField(blank=True, db_column='NgayKhoa', null=True, verbose_name='Ngày khóa')),
                ('ma_du_kien_dt', models.ForeignKey(db_column='MaDuKienDT', on_delete=django.db.models.deletion.CASCADE, related_name='dot_xep_list', to='scheduling.dukiendt', verbose_name='Dự kiến ĐT')),
            ],
            options={
                'verbose_name': 'Đợt xếp lịch',
                'verbose_name_plural': 'Đợt xếp lịch',
                'db_table': 'tb_DOT_XEP',
                'ordering': ['-ngay_tao'],
            },
        ),
        migrations.CreateModel(
            name='GiangVien',
            fields=[
                ('ma_gv', models.CharField(db_column='MaGV', max_length=12, primary_key=True, serialize=False, verbose_name='Mã giảng viên')),
                ('ten_gv', models.CharField(db_column='TenGV', max_length=200, verbose_name='Tên giảng viên')),
                ('loai_gv', models.CharField(blank=True, db_column='LoaiGV', max_length=100, null=True, verbose_name='Loại GV')),
                ('ghi_chu', models.CharField(blank=True, db_column='GhiChu', max_length=300, null=True, verbose_name='Ghi chú')),
                ('email', models.CharField(blank=True, db_column='Email', max_length=200, null=True, verbose_name='Email')),
                ('ma_bo_mon', models.ForeignKey(db_column='MaBoMon', on_delete=django.db.models.deletion.CASCADE, related_name='giang_vien_list', to='scheduling.bomon', verbose_name='Bộ môn')),
            ],
            options={
                'verbose_name': 'Giảng viên',
                'verbose_name_plural': 'Giảng viên',
                'db_table': 'tb_GIANG_VIEN',
                'ordering': ['ma_gv'],
            },
        ),
        migrations.AddField(
            model_name='bomon',
            name='ma_khoa',
            field=models.ForeignKey(db_column='MaKhoa', on_delete=django.db.models.deletion.CASCADE, related_name='bo_mon_list', to='scheduling.khoa', verbose_name='Khoa'),
        ),
        migrations.CreateModel(
            name='LopMonHoc',
            fields=[
                ('ma_lop', models.CharField(db_column='MaLop', max_length=12, primary_key=True, serialize=False, verbose_name='Mã lớp')),
                ('nhom_mh', models.SmallIntegerField(db_column='Nhom_MH', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Nhóm')),
                ('to_mh', models.SmallIntegerField(blank=True, db_column='To_MH', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tổ')),
                ('so_luong_sv', models.SmallIntegerField(blank=True, db_column='SoLuongSV', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Số lượng SV')),
                ('he_dao_tao', models.CharField(blank=True, db_column='HeDaoTao', max_length=200, null=True, verbose_name='Hệ đào tạo')),
                ('ngon_ngu', models.CharField(blank=True, db_column='NgonNgu', max_length=50, null=True, verbose_name='Ngôn ngữ')),
                ('thiet_bi_yeu_cau', models.CharField(blank=True, db_column='ThietBiYeuCau', max_length=400, null=True, verbose_name='Thiết bị yêu cầu')),
                ('so_ca_tuan', models.SmallIntegerField(db_column='SoCaTuan', default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Số ca/tuần')),
                ('ma_mon_hoc', models.ForeignKey(db_column='MaMonHoc', on_delete=django.db.models.deletion.CASCADE, related_name='lop_list', to='scheduling.monhoc', verbose_name='Môn học')),
            ],
            options={
                'verbose_name': 'Lớp môn học',
                'verbose_name_plural': 'Lớp môn học',
                'db_table': 'tb_LOP_MONHOC',
                'ordering': ['ma_lop'],
            },
        ),
        migrations.CreateModel(
            name='GVDayMon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_gv', models.ForeignKey(db_column='MaGV', on_delete=django.db.models.deletion.CASCADE, related_name='mon_day_list', to='scheduling.giangvien', verbose_name='Giảng viên')),
                ('ma_mon_hoc', models.ForeignKey(db_column='MaMonHoc', on_delete=django.db.models.deletion.CASCADE, related_name='gv_day_list', to='scheduling.monhoc', verbose_name='Môn học')),
            ],
            options={
                'verbose_name': 'GV dạy môn',
                'verbose_name_plural': 'GV dạy môn',
                'db_table': 'tb_GV_DAY_MON',
            },
        ),
        migrations.CreateModel(
            name='PhanCong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_dot', models.ForeignKey(db_column='MaDot', on_delete=django.db.models.deletion.CASCADE, related_name='phan_cong_list', to='scheduling.dotxep', verbose_name='Đợt xếp')),
                ('ma_gv', models.ForeignKey(blank=True, db_column='MaGV', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phan_cong_list', to='scheduling.giangvien', verbose_name='Giảng viên')),
                ('ma_lop', models.ForeignKey(db_column='MaLop', on_delete=django.db.models.deletion.CASCADE, related_name='phan_cong_list', to='scheduling.lopmonhoc', verbose_name='Lớp môn học')),
            ],
            options={
                'verbose_name': 'Phân công',
                'verbose_name_plural': 'Phân công giảng dạy',
                'db_table': 'tb_PHAN_CONG',
            },
        ),
        migrations.CreateModel(
            name='RangBuocTrongDot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_dot', models.ForeignKey(db_column='MaDot', on_delete=django.db.models.deletion.CASCADE, related_name='rang_buoc_list', to='scheduling.dotxep', verbose_name='Đợt xếp')),
                ('ma_rang_buoc', models.ForeignKey(db_column='MaRangBuoc', on_delete=django.db.models.deletion.CASCADE, related_name='dot_ap_dung_list', to='scheduling.rangbuocmem', verbose_name='Ràng buộc')),
            ],
            options={
                'verbose_name': 'Ràng buộc trong đợt',
                'verbose_name_plural': 'Ràng buộc trong đợt',
                'db_table': 'tb_RANG_BUOC_TRONG_DOT',
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('time_slot_id', models.CharField(db_column='TimeSlotID', max_length=10, primary_key=True, serialize=False, verbose_name='TimeSlot ID')),
                ('thu', models.SmallIntegerField(db_column='Thu', validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(8)], verbose_name='Thứ (2-8, 8=CN)')),
                ('ca', models.ForeignKey(db_column='Ca', on_delete=django.db.models.deletion.CASCADE, related_name='time_slot_list', to='scheduling.khungtg', verbose_name='Ca')),
            ],
            options={
                'verbose_name': 'Time Slot',
                'verbose_name_plural': 'Time Slots',
                'db_table': 'tb_TIME_SLOT',
                'ordering': ['thu', 'ca'],
            },
        ),
        migrations.CreateModel(
            name='ThoiKhoaBieu',
            fields=[
                ('ma_tkb', models.CharField(db_column='MaTKB', max_length=15, primary_key=True, serialize=False, verbose_name='Mã TKB')),
                ('tuan_hoc', models.CharField(blank=True, db_column='TuanHoc', max_length=64, null=True, verbose_name='Tuần học')),
                ('ngay_bd', models.DateTimeField(blank=True, db_column='NgayBD', null=True, verbose_name='Ngày bắt đầu')),
                ('ngay_kt', models.DateTimeField(blank=True, db_column='NgayKT', null=True, verbose_name='Ngày kết thúc')),
                ('ma_dot', models.ForeignKey(db_column='MaDot', on_delete=django.db.models.deletion.CASCADE, related_name='tkb_list', to='scheduling.dotxep', verbose_name='Đợt xếp')),
                ('ma_lop', models.ForeignKey(db_column='MaLop', on_delete=django.db.models.deletion.CASCADE, related_name='tkb_list', to='scheduling.lopmonhoc', verbose_name='Lớp môn học')),
                ('ma_phong', models.ForeignKey(db_column='MaPhong', on_delete=django.db.models.deletion.CASCADE, related_name='tkb_list', to='scheduling.phonghoc', verbose_name='Phòng học')),
                ('time_slot_id', models.ForeignKey(db_column='TimeSlotID', on_delete=django.db.models.deletion.CASCADE, related_name='tkb_list', to='scheduling.timeslot', verbose_name='Time slot')),
            ],
            options={
                'verbose_name': 'Thời khóa biểu',
                'verbose_name_plural': 'Thời khóa biểu',
                'db_table': 'tb_TKB',
                'ordering': ['ma_dot', 'time_slot_id__thu', 'time_slot_id__ca'],
            },
        ),
        migrations.CreateModel(
            name='NguyenVong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_dot', models.ForeignKey(db_column='MaDot', on_delete=django.db.models.deletion.CASCADE, related_name='nguyen_vong_list', to='scheduling.dotxep', verbose_name='Đợt xếp')),
                ('ma_gv', models.ForeignKey(db_column='MaGV', on_delete=django.db.models.deletion.CASCADE, related_name='nguyen_vong_list', to='scheduling.giangvien', verbose_name='Giảng viên')),
                ('time_slot_id', models.ForeignKey(db_column='TimeSlotID', on_delete=django.db.models.deletion.CASCADE, related_name='nguyen_vong_list', to='scheduling.timeslot', verbose_name='Time slot')),
            ],
            options={
                'verbose_name': 'Nguyện vọng',
                'verbose_name_plural': 'Nguyện vọng giảng viên',
                'db_table': 'tb_NGUYEN_VONG',
            },
        ),
        migrations.AddIndex(
            model_name='giangvien',
            index=models.Index(fields=['ma_bo_mon'], name='IX_GV_MaBoMon'),
        ),
        migrations.AlterUniqueTogether(
            name='bomon',
            unique_together={('ma_khoa', 'ten_bo_mon')},
        ),
        migrations.AddIndex(
            model_name='lopmonhoc',
            index=models.Index(fields=['ma_mon_hoc'], name='IX_LMH_MaMonHoc'),
        ),
        migrations.AlterUniqueTogether(
            name='lopmonhoc',
            unique_together={('ma_mon_hoc', 'nhom_mh', 'to_mh')},
        ),
        migrations.AlterUniqueTogether(
            name='gvdaymon',
            unique_together={('ma_mon_hoc', 'ma_gv')},
        ),
        migrations.AddIndex(
            model_name='phancong',
            index=models.Index(fields=['ma_gv'], name='IX_PC_MaGV'),
        ),
        migrations.AddIndex(
            model_name='phancong',
            index=models.Index(fields=['ma_lop'], name='IX_PC_MaLop'),
        ),
        migrations.AddIndex(
            model_name='phancong',
            index=models.Index(fields=['ma_dot'], name='IX_PC_MaDot'),
        ),
        migrations.AlterUniqueTogether(
            name='phancong',
            unique_together={('ma_dot', 'ma_lop')},
        ),
        migrations.AlterUniqueTogether(
            name='rangbuoctrongdot',
            unique_together={('ma_dot', 'ma_rang_buoc')},
        ),
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together={('thu', 'ca')},
        ),
        migrations.AddIndex(
            model_name='thoikhoabieu',
            index=models.Index(fields=['ma_dot'], name='IX_TKB_MaDot'),
        ),
        migrations.AddIndex(
            model_name='thoikhoabieu',
            index=models.Index(fields=['ma_lop'], name='IX_TKB_MaLop'),
        ),
        migrations.AddIndex(
            model_name='thoikhoabieu',
            index=models.Index(fields=['time_slot_id'], name='IX_TKB_TimeSlotID'),
        ),
        migrations.AlterUniqueTogether(
            name='thoikhoabieu',
            unique_together={('ma_dot', 'ma_lop', 'ma_phong', 'time_slot_id')},
        ),
        migrations.AlterUniqueTogether(
            name='nguyenvong',
            unique_together={('ma_gv', 'ma_dot', 'time_slot_id')},
        ),
    ]
