# Generated by Django 5.2.6 on 2025-12-23 08:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_alter_gvdaymon_id_alter_nguyenvong_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NgayNghiCoDinh',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ten_ngay_nghi', models.CharField(db_column='TenNgayNghi', max_length=100, verbose_name='Tên ngày nghỉ')),
                ('ngay', models.CharField(db_column='Ngay', max_length=5, verbose_name='Ngày (MM-DD)')),
                ('ghi_chu', models.CharField(blank=True, db_column='GhiChu', max_length=200, null=True, verbose_name='Ghi chú')),
            ],
            options={
                'verbose_name': 'Ngày nghỉ cố định',
                'verbose_name_plural': 'Ngày nghỉ cố định',
                'db_table': 'tb_NGAY_NGHI_CO_DINH',
                'ordering': ['ngay'],
            },
        ),
        migrations.CreateModel(
            name='NgayNghiDot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ngay_bd', models.DateField(db_column='NgayBD', verbose_name='Ngày bắt đầu nghỉ')),
                ('so_ngay_nghi', models.SmallIntegerField(db_column='SoNgayNghi', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Số ngày nghỉ')),
                ('tuan_bd', models.SmallIntegerField(blank=True, db_column='TuanBD', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(15)], verbose_name='Tuần bắt đầu (tham khảo)')),
                ('tuan_kt', models.SmallIntegerField(blank=True, db_column='TuanKT', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(15)], verbose_name='Tuần kết thúc (tham khảo)')),
                ('ten_ngay_nghi', models.CharField(blank=True, db_column='TenNgayNghi', max_length=100, null=True, verbose_name='Tên khoảng nghỉ')),
                ('ghi_chu', models.CharField(blank=True, db_column='GhiChu', max_length=200, null=True, verbose_name='Ghi chú')),
            ],
            options={
                'verbose_name': 'Ngày nghỉ theo đợt',
                'verbose_name_plural': 'Ngày nghỉ theo đợt',
                'db_table': 'tb_NGAY_NGHI_DOT',
            },
        ),
        migrations.AddField(
            model_name='phancong',
            name='tuan_bd',
            field=models.SmallIntegerField(db_column='TuanBD', default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='Tuần bắt đầu (1-20)'),
        ),
        migrations.AddField(
            model_name='phancong',
            name='tuan_kt',
            field=models.SmallIntegerField(db_column='TuanKT', default=15, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='Tuần kết thúc (>= TuanBD, ≤ 20)'),
        ),
        migrations.AddField(
            model_name='thoikhoabieu',
            name='ghi_chu',
            field=models.CharField(blank=True, db_column='GhiChu', max_length=200, null=True, verbose_name='Ghi chú'),
        ),
        migrations.AddField(
            model_name='thoikhoabieu',
            name='ngay_tao',
            field=models.DateTimeField(auto_now_add=True, db_column='NgayTao', null=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='dotxep',
            name='ngay_tao',
            field=models.DateTimeField(auto_now_add=True, db_column='NgayTao', null=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='thoikhoabieu',
            name='ma_phong',
            field=models.ForeignKey(blank=True, db_column='MaPhong', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tkb_list', to='scheduling.phonghoc', verbose_name='Phòng học'),
        ),
        migrations.AlterField(
            model_name='thoikhoabieu',
            name='ngay_bd',
            field=models.DateField(blank=True, db_column='NgayBD', null=True, verbose_name='Ngày bắt đầu khoá học'),
        ),
        migrations.AlterField(
            model_name='thoikhoabieu',
            name='ngay_kt',
            field=models.DateField(blank=True, db_column='NgayKT', null=True, verbose_name='Ngày kết thúc khoá học'),
        ),
        migrations.AlterField(
            model_name='thoikhoabieu',
            name='tuan_hoc',
            field=models.CharField(blank=True, db_column='TuanHoc', max_length=64, null=True, verbose_name='Pattern tuần học'),
        ),
        migrations.AddIndex(
            model_name='phancong',
            index=models.Index(fields=['ma_dot', 'ma_gv'], name='IX_PC_MaDot_MaGV'),
        ),
        migrations.AddIndex(
            model_name='thoikhoabieu',
            index=models.Index(fields=['ngay_bd'], name='IX_TKB_NgayBD'),
        ),
        migrations.AddIndex(
            model_name='thoikhoabieu',
            index=models.Index(fields=['ma_dot', 'ma_lop'], name='IX_TKB_MaDot_MaLop'),
        ),
        migrations.AddField(
            model_name='ngaynghidot',
            name='ma_dot',
            field=models.ForeignKey(db_column='MaDot', on_delete=django.db.models.deletion.CASCADE, related_name='ngay_nghi_list', to='scheduling.dotxep', verbose_name='Đợt xếp'),
        ),
        migrations.AddIndex(
            model_name='ngaynghidot',
            index=models.Index(fields=['ma_dot'], name='IX_NGAYNGHI_MaDot'),
        ),
        migrations.AlterUniqueTogether(
            name='ngaynghidot',
            unique_together={('ma_dot', 'ngay_bd', 'so_ngay_nghi')},
        ),
    ]
