# Generated by Django 5.2.6 on 2025-12-27 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0003_ngaynghicodinh_ngaynghidot_phancong_tuan_bd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rangbuoctrongdot',
            name='trong_so',
            field=models.FloatField(db_column='TrongSo', default=1.0, help_text='Trọng số riêng cho đợt này (override trọng số global)', verbose_name='Trọng số override'),
        ),
        migrations.AlterField(
            model_name='dukiendt',
            name='hoc_ky',
            field=models.SmallIntegerField(choices=[(1, 'Học kỳ 1'), (2, 'Học kỳ 2'), (3, 'Học kỳ Hè')], db_column='HocKy', verbose_name='Học kỳ'),
        ),
    ]
