# Generated by Django 5.2.6 on 2026-01-01 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0004_rangbuoctrongdot_trong_so_alter_dukiendt_hoc_ky'),
    ]

    operations = [
        migrations.CreateModel(
            name='TKBLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ma_tkb', models.CharField(db_column='MaTKB', max_length=15, verbose_name='Mã TKB')),
                ('action', models.CharField(choices=[('CREATE', 'Tạo mới'), ('UPDATE', 'Cập nhật'), ('DELETE', 'Xóa'), ('RESTORE', 'Phục hồi'), ('SWAP', 'Hoán đổi')], db_column='Action', max_length=10, verbose_name='Hành động')),
                ('user', models.CharField(blank=True, db_column='User', max_length=100, null=True, verbose_name='Người thực hiện')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_column='Timestamp', verbose_name='Thời gian')),
                ('old_data', models.JSONField(blank=True, db_column='OldData', null=True, verbose_name='Dữ liệu cũ (JSON)')),
                ('new_data', models.JSONField(blank=True, db_column='NewData', null=True, verbose_name='Dữ liệu mới (JSON)')),
                ('reason', models.CharField(blank=True, db_column='Reason', max_length=500, null=True, verbose_name='Lý do')),
            ],
            options={
                'verbose_name': 'Log TKB',
                'verbose_name_plural': 'Log TKB',
                'db_table': 'tb_TKB_LOG',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='thoikhoabieu',
            name='is_deleted',
            field=models.BooleanField(db_column='IsDeleted', default=False, verbose_name='Đã xóa (soft delete)'),
        ),
        migrations.AlterField(
            model_name='bomon',
            name='ma_bo_mon',
            field=models.CharField(blank=True, db_column='MaBoMon', max_length=12, primary_key=True, serialize=False, verbose_name='Mã bộ môn'),
        ),
        migrations.AlterField(
            model_name='dotxep',
            name='ma_dot',
            field=models.CharField(blank=True, db_column='MaDot', max_length=20, primary_key=True, serialize=False, verbose_name='Mã đợt'),
        ),
        migrations.AlterField(
            model_name='dukiendt',
            name='ma_du_kien_dt',
            field=models.CharField(blank=True, db_column='MaDuKienDT', max_length=15, primary_key=True, serialize=False, verbose_name='Mã dự kiến ĐT'),
        ),
        migrations.AlterField(
            model_name='giangvien',
            name='ma_gv',
            field=models.CharField(blank=True, db_column='MaGV', max_length=12, primary_key=True, serialize=False, verbose_name='Mã giảng viên'),
        ),
        migrations.AlterField(
            model_name='khoa',
            name='ma_khoa',
            field=models.CharField(blank=True, db_column='MaKhoa', max_length=12, primary_key=True, serialize=False, verbose_name='Mã khoa'),
        ),
        migrations.AlterField(
            model_name='lopmonhoc',
            name='ma_lop',
            field=models.CharField(blank=True, db_column='MaLop', max_length=12, primary_key=True, serialize=False, verbose_name='Mã lớp'),
        ),
        migrations.AlterField(
            model_name='rangbuocmem',
            name='ma_rang_buoc',
            field=models.CharField(blank=True, db_column='MaRangBuoc', max_length=15, primary_key=True, serialize=False, verbose_name='Mã ràng buộc'),
        ),
        migrations.AlterField(
            model_name='thoikhoabieu',
            name='ma_tkb',
            field=models.CharField(blank=True, db_column='MaTKB', max_length=15, primary_key=True, serialize=False, verbose_name='Mã TKB'),
        ),
        migrations.AddIndex(
            model_name='thoikhoabieu',
            index=models.Index(fields=['is_deleted'], name='IX_TKB_IsDeleted'),
        ),
        migrations.AddIndex(
            model_name='tkblog',
            index=models.Index(fields=['ma_tkb'], name='IX_TKBLOG_MaTKB'),
        ),
        migrations.AddIndex(
            model_name='tkblog',
            index=models.Index(fields=['timestamp'], name='IX_TKBLOG_Time'),
        ),
        migrations.AddIndex(
            model_name='tkblog',
            index=models.Index(fields=['action'], name='IX_TKBLOG_Action'),
        ),
    ]
