# Generated by Django 5.2.6 on 2026-01-24 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0005_tkblog_thoikhoabieu_is_deleted_alter_bomon_ma_bo_mon_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bomon',
            options={'default_permissions': (), 'ordering': ['ma_bo_mon'], 'verbose_name': 'Bộ môn', 'verbose_name_plural': 'Các Bộ môn'},
        ),
        migrations.AlterModelOptions(
            name='dotxep',
            options={'default_permissions': (), 'ordering': ['-ngay_tao'], 'verbose_name': 'Đợt xếp lịch', 'verbose_name_plural': 'Đợt xếp lịch'},
        ),
        migrations.AlterModelOptions(
            name='dukiendt',
            options={'default_permissions': (), 'ordering': ['-nam_hoc', '-hoc_ky'], 'verbose_name': 'Dự kiến đào tạo', 'verbose_name_plural': 'Dự kiến đào tạo'},
        ),
        migrations.AlterModelOptions(
            name='giangvien',
            options={'default_permissions': (), 'ordering': ['ma_gv'], 'verbose_name': 'Giảng viên', 'verbose_name_plural': 'Giảng viên'},
        ),
        migrations.AlterModelOptions(
            name='gvdaymon',
            options={'default_permissions': (), 'verbose_name': 'GV dạy môn', 'verbose_name_plural': 'GV dạy môn'},
        ),
        migrations.AlterModelOptions(
            name='khoa',
            options={'default_permissions': (), 'ordering': ['ma_khoa'], 'verbose_name': 'Khoa', 'verbose_name_plural': 'Các Khoa'},
        ),
        migrations.AlterModelOptions(
            name='khungtg',
            options={'default_permissions': (), 'ordering': ['ma_khung_gio'], 'verbose_name': 'Khung thời gian', 'verbose_name_plural': 'Khung thời gian'},
        ),
        migrations.AlterModelOptions(
            name='lopmonhoc',
            options={'default_permissions': (), 'ordering': ['ma_lop'], 'verbose_name': 'Lớp môn học', 'verbose_name_plural': 'Lớp môn học'},
        ),
        migrations.AlterModelOptions(
            name='monhoc',
            options={'default_permissions': (), 'ordering': ['ma_mon_hoc'], 'verbose_name': 'Môn học', 'verbose_name_plural': 'Môn học'},
        ),
        migrations.AlterModelOptions(
            name='ngaynghicodinh',
            options={'default_permissions': (), 'ordering': ['ngay'], 'verbose_name': 'Ngày nghỉ cố định', 'verbose_name_plural': 'Ngày nghỉ cố định'},
        ),
        migrations.AlterModelOptions(
            name='ngaynghidot',
            options={'default_permissions': (), 'verbose_name': 'Ngày nghỉ theo đợt', 'verbose_name_plural': 'Ngày nghỉ theo đợt'},
        ),
        migrations.AlterModelOptions(
            name='nguyenvong',
            options={'default_permissions': (), 'verbose_name': 'Nguyện vọng', 'verbose_name_plural': 'Nguyện vọng giảng viên'},
        ),
        migrations.AlterModelOptions(
            name='phancong',
            options={'default_permissions': (), 'verbose_name': 'Phân công', 'verbose_name_plural': 'Phân công giảng dạy'},
        ),
        migrations.AlterModelOptions(
            name='phonghoc',
            options={'default_permissions': (), 'ordering': ['ma_phong'], 'verbose_name': 'Phòng học', 'verbose_name_plural': 'Phòng học'},
        ),
        migrations.AlterModelOptions(
            name='rangbuocmem',
            options={'default_permissions': (), 'ordering': ['ma_rang_buoc'], 'verbose_name': 'Ràng buộc mềm', 'verbose_name_plural': 'Ràng buộc mềm'},
        ),
        migrations.AlterModelOptions(
            name='rangbuoctrongdot',
            options={'default_permissions': (), 'verbose_name': 'Ràng buộc trong đợt', 'verbose_name_plural': 'Ràng buộc trong đợt'},
        ),
        migrations.AlterModelOptions(
            name='timeslot',
            options={'default_permissions': (), 'ordering': ['thu', 'ca'], 'verbose_name': 'Time Slot', 'verbose_name_plural': 'Time Slots'},
        ),
    ]
