# Generated by Django 5.2.6 on 2026-01-24 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0006_hide_data_model_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tkblog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Tạo mới'), ('UPDATE', 'Cập nhật'), ('MOVE', 'Di chuyển'), ('DELETE', 'Xóa'), ('RESTORE', 'Phục hồi'), ('SWAP', 'Hoán đổi')], db_column='Action', max_length=10, verbose_name='Hành động'),
        ),
    ]
