# Generated by Django 5.2.6 on 2026-01-24 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
